[package]
name = "riscv-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
elf = { version = "0.7.4" }
env_logger = "0.11.3"
log = "0.4"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
